# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |main|

    main.vm.define "master" do |config|
      config.vm.box = "generic/ubuntu1804"
    
      config.vm.network "private_network", ip: "192.168.56.10"
    
      config.vm.provider "virtualbox" do |v|
        v.name = "vagrant_xcat_master"
        v.check_guest_additions = false
        v.memory = 1024
        v.cpus = 1
        v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
      end
    
      config.vm.provision "shell", inline: <<-SHELL
        wget -O - "http://xcat.org/files/xcat/repos/apt/apt.key" | apt-key add -
        echo "deb [arch=amd64] http://xcat.org/files/xcat/repos/apt/latest/xcat-core bionic main\ndeb [arch=amd64] http://xcat.org/files/xcat/repos/apt/latest/xcat-dep bionic main" > /etc/apt/sources.list.d/xcat.list
        apt-get update
        apt-get install -y xcat
        source /etc/profile.d/xcat.sh
        yes | sudo /opt/xcat/share/xcat/scripts/setup-local-client.sh vagrant
        lsxcatd -a
        sudo systemctl enable xcatd.service

        # enable rest api ssl support
        sudo a2enmod ssl
        ln -s ../sites-available/default-ssl.conf  /etc/apache2/sites-enabled/ssl.conf
        sudo service apache2 restart

        # verify ssl is loaded
        sudo apache2ctl -t -D DUMP_MODULES | grep ssl

        apt-get install libjson-perl

        # set password for root login
        tabch key=xcat,username=root passwd.password=root

        # add non root user
        useradd -u 1101 user1
        (echo 'pass'; echo 'pass') | passwd user1
        tabch key=xcat,username=user1 passwd.password=pass
        mkdef -t policy 6 name=user1 rule=allow

        # register node
        mkdef -t node node1 groups=all ip=192.168.56.11 installnic=mac primarynic=mac mac=aa:06:fd:af:4d:c9


      SHELL
    end

    main.vm.define "node1" do |config|
      config.vm.box = "generic/alpine38"
      config.vm.network "private_network", ip: "192.168.56.11", mac: "AA06FDAF4DC9"
      config.vm.provider "virtualbox" do |v|
        v.name = "vagrant_xcat_node1"
        v.check_guest_additions = false
        v.memory = 256
        v.cpus = 1
        v.customize ["modifyvm", :id, "--cpuexecutioncap", "25"]
      end
    end
end