# -*- mode: ruby -*-
# vi: set ft=ruby :

$SETUPDB = <<-'BLOCK'
create database slurm_acct_db;
create user 'slurm'@'localhost';
set password for 'slurm'@'localhost' = password('slurmdbpass');
grant usage on *.* to 'slurm'@'localhost';
grant all privileges on slurm_acct_db.* to 'slurm'@'localhost';
flush privileges;
BLOCK

$SLURMCONF = <<-'BLOCK'
ClusterName=cluster
ControlMachine=slurm
ControlAddr=192.168.56.9
#ControlAddr=
#BackupController=
#BackupAddr=
#
SlurmUser=slurm
#SlurmdUser=root
SlurmctldPort=6817
SlurmdPort=6818
AuthType=auth/munge
#JobCredentialPrivateKey=
#JobCredentialPublicCertificate=
StateSaveLocation=/var/spool/slurm/ctld
SlurmdSpoolDir=/var/spool/slurm/d
SwitchType=switch/none
MpiDefault=none
SlurmctldPidFile=/var/run/slurmctld.pid
SlurmdPidFile=/var/run/slurmd.pid
ProctrackType=proctrack/pgid
#PluginDir=
#FirstJobId=
ReturnToService=0
#MaxJobCount=
#PlugStackConfig=
#PropagatePrioProcess=
#PropagateResourceLimits=
#PropagateResourceLimitsExcept=
#Prolog=
#Epilog=
#SrunProlog=
#SrunEpilog=
#TaskProlog=
#TaskEpilog=
#TaskPlugin=
#TrackWCKey=no
#TreeWidth=50
#TmpFS=
#UsePAM=
#
# TIMERS
SlurmctldTimeout=300
SlurmdTimeout=300
InactiveLimit=0
MinJobAge=300
KillWait=30
Waittime=0
#
# SCHEDULING
SchedulerType=sched/backfill
#SchedulerAuth=
#SelectType=select/linear
#PriorityType=priority/multifactor
#PriorityDecayHalfLife=14-0
#PriorityUsageResetPeriod=14-0
#PriorityWeightFairshare=100000
#PriorityWeightAge=1000
#PriorityWeightPartition=10000
#PriorityWeightJobSize=1000
#PriorityMaxAge=1-0
#
# LOGGING
SlurmctldDebug=info
SlurmctldLogFile=/var/log/slurmctld.log
SlurmdDebug=info
SlurmdLogFile=/var/log/slurmd.log
JobCompType=jobcomp/none
#JobCompLoc=
#
# ACCOUNTING
#JobAcctGatherType=jobacct_gather/linux
#JobAcctGatherFrequency=30
#
#AccountingStorageType=accounting_storage/slurmdbd
#AccountingStorageHost=
#AccountingStorageLoc=
#AccountingStoragePass=
#AccountingStorageUser=
#


# COMPUTE NODES
NodeName=node[1-2] CPUs=1 State=UNKNOWN
PartitionName=debug Nodes=ALL Default=YES MaxTime=INFINITE State=UP
BLOCK

$PROVISION_SLURM = <<-SHELL
apt-get update
apt-get install -y mariadb-server slurmd slurm-client slurmctld
cat << EOF | sudo mysql -u root
#{$SETUPDB}
EOF
cat << EOF > /etc/slurm-llnl/slurm.conf
#{$SLURMCONF}
EOF
exit
SHELL

$PROVISION_XCAT = <<-SHELL
wget -O - "http://xcat.org/files/xcat/repos/apt/apt.key" | apt-key add -
echo "deb [arch=amd64] http://xcat.org/files/xcat/repos/apt/latest/xcat-core bionic main\ndeb [arch=amd64] http://xcat.org/files/xcat/repos/apt/latest/xcat-dep bionic main" > /etc/apt/sources.list.d/xcat.list
apt-get update
apt-get install -y xcat
source /etc/profile.d/xcat.sh
yes | sudo /opt/xcat/share/xcat/scripts/setup-local-client.sh vagrant
lsxcatd -a
sudo systemctl enable xcatd.service

# enable rest api ssl support
sudo a2enmod ssl
ln -s ../sites-available/default-ssl.conf  /etc/apache2/sites-enabled/ssl.conf
sudo service apache2 restart

# verify ssl is loaded
sudo apache2ctl -t -D DUMP_MODULES | grep ssl

apt-get install libjson-perl

# set password for root login
tabch key=xcat,username=root passwd.password=root

# add non root user
useradd -u 1101 user1
(echo 'pass'; echo 'pass') | passwd user1
tabch key=xcat,username=user1 passwd.password=pass
mkdef -t policy 6 name=user1 rule=allow

# register node
mkdef -t node node1 groups=all ip=192.168.56.11 installnic=mac primarynic=mac mac=aa:06:fd:af:4d:c9

SHELL

Vagrant.configure("2") do |main|

    main.vm.define "xcat" do |config|
      config.vm.box = "generic/ubuntu1804"
    
      config.vm.network "private_network", ip: "192.168.56.10"
      config.vm.hostname = "xcat"
    
      config.vm.provider "virtualbox" do |v|
        v.name = "vagrant_trex_xcat"
        v.check_guest_additions = false
        v.memory = 1024
        v.cpus = 1
        v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
      end
    
      config.vm.provision "shell", inline: $PROVVISION_XCAT
    end

    main.vm.define "slurm" do |config|
      config.vm.box = "generic/ubuntu1804"
    
      config.vm.network "private_network", ip: "192.168.56.9"
      config.vm.hostname = "slurm"
    
      config.vm.provider "virtualbox" do |v|
        v.name = "vagrant_trex_slurm"
        v.check_guest_additions = false
        v.memory = 1024
        v.cpus = 1
        v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
      end

      config.vm.provision "shell", inline: $PROVISION_SLURM
    end

    main.vm.define "node1" do |config|
      config.vm.box = "generic/alpine38"
      config.vm.network "private_network", ip: "192.168.56.11", mac: "AA06FDAF4DC9"
      config.vm.hostname = "node1"
      config.vm.provider "virtualbox" do |v|
        v.name = "vagrant_trex_node1"
        v.check_guest_additions = false
        v.memory = 256
        v.cpus = 1
        v.customize ["modifyvm", :id, "--cpuexecutioncap", "25"]
      end
    end
end