openapi: 3.0.3
info:
    title: Batch Server API
    description: Batch Server API
    version: 0.1.0
    contact:
        name: Nico Tippmann
        url: megware.com
        email: info@megware.com
    license:
        name: TODO
servers:
    - url: /v1
      description: batch server

paths:
  /slurm/nodes/state:
    post:
      operationId: "batch_rest_server.api.slurm.nodes.setState"
      tags:
        - "slurm"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              items:
                $ref: "#/components/schemas/NodeStates"
        required: true
      summary: "Set node(s) state"
      description: "Sets the slurm state for all specified nodes"
      responses:
        "200":
          description: "State Set"
        "400":
          description: "Invalid Request"
          
components:
  schemas:
    NodeStates:
      description: Node States
      properties:
        nodes:
          type: array
        state:
          $ref: "#/components/schemas/EnumSlurmScontrolStateOptions"
        reason:
          type: string
    EnumSlurmScontrolStateOptions:
      type: string
      enum:
        - cancel_reboot
        - down
        - drain
        - fail
        - future
        - resume
        - noresp
        - power_down
        - power_up
        - undrain
  parameters:
    NodeList:
      name: nodes
      in: query
      schema:
        type: string
      description: List of comma-separated nodes
    State:
      name: state
      in: query
      schema:
        $ref: "#/components/schemas/EnumSlurmScontrolStateOptions"
      description: State to be set  
          
