openapi: 3.0.3
info:
    title: Batch Server API
    description: Batch Server API
    version: 0.1.0
    contact:
        name: Nico Tippmann
        url: megware.com
        email: info@megware.com
    license:
        name: TODO
servers:
    - url: /v1
      description: batch server

paths:
  /slurm/nodes/state:
    post:
      operationId: "batch_rest_server.api.slurm.nodes.setState"
      tags:
        - "slurm"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              items:
                $ref: "#/components/schemas/NodeStates"
        required: true
      summary: "Set node(s) state"
      description: "Sets the slurm state for all specified nodes"
      responses:
        "200":
          description: "State Set"
        "400":
          description: "Invalid Request"
          
components:
  schemas:
    NodeStates:
      description: Node States
      properties:
        nodes:
          type: array
        state:
          $ref: "#/components/schemas/EnumSlurmStates"
    EnumSlurmStates:
      type: string
      enum:
        - alloc
        - allocated
        - cloud
        - comp
        - completing
        - down-drain
        - drained
        - draining
        - fail
        - future
        - futr
        - idle
        - maint
        - mix
        - mixed
        - no_respond
        - npc
        - perfctrs
        - planned
        - power_down
        - powering_down
        - powered_down
        - powering_up
        - reboot_issued
        - reboot_requested
        - resv
        - reserved
        - unk
        - unknown
  parameters:
    NodeList:
      name: nodes
      in: query
      schema:
        type: string
      description: List of comma-separated nodes
    State:
      name: state
      in: query
      schema:
        $ref: "#/components/schemas/EnumSlurmStates"
      description: State to be set  
          
